### ISSUE TITLE
Add asset generation tests

### ISSUE THREAD

**Issue by aufi** [konveyor-ecosystem/kantra-cli-tests#61]
There is a new asset-generation feature being added to kantra, added in https://github.com/konveyor/kantra/pull/435

Test scenarios should be defined, approved, written as part of this repository.

Selected subset of those tests should be marked as TIER0 and added to upstream CI execution.

**Comment by jordigilh** [comment]
Test 1:
* Prerequisites:
  * Local copy of PCF V3 manifest as defined here: https://raw.githubusercontent.com/gciavarrini/demo-kantra-asset-gen/refs/heads/main/cf-nodejs-app.yaml to ./cf-nodejs-app.yaml
  * Kantra CLI with the generate and discover subcommands supporting PCF V3

 * Steps:

(1) Run command: `kantra discover cloud-foundry --input ./cf-nodejs-app.yaml --output discover.yaml`
(2) Validate that the generated file contains the following content: 
```
name: cf-nodejs
randomRoute: true
timeout: 60
buildPacks:
- docker://my-registry-a.corp/nodejs
- docker://my-registry-b.corp/dynatrace
instances: 1
```
(3) Copy the helm found in [https://github.com/gciavarrini/demo-kantra-asset-gen/tree/main/helm_sample](https://github.com/gciavarrini/demo-kantra-asset-gen/tree/main/helm_sample) to `./helm_sample`
(4) Run command `kantra generate helm --chart-dir ./helm_sample --input discover.yaml --output-dir ./manifests`
(5) Validate the generated file  in `./manifests` matches the expected value:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: cf-nodejs-config
data:
  SPACE:
  VERSION:
  RANDOM_ROUTE: true
  TIMEOUT: "60"
  BUILD_PACKS: |
    - docker://my-registry-a.corp/nodejs
    - docker://my-registry-b.corp/dynatrace
  INSTANCES: "1"

```
